### ISSUE TITLE
Version is bumped after trial release

### ISSUE THREAD

**Issue by Altreus** [dagolden/Dist-Zilla-Plugin-BumpVersionAfterRelease#18]
dzil release --trial

This still causes the version to be bumped, which I would argue is not the desired behaviour (because there might be further things to change before you release this for real)

**Comment by dagolden** [comment]
That's by design.  Once you ship something to CPAN, you can never ship the same filename again.  Therefore, you need to bump the version so the *next* trial release has a unique name.

It's common for CPAN modules to have successive trial releases with increasing version numbers.  See, for example, the [Moose change log](https://metacpan.org/changes/distribution/Moose).
